name: nice_scrollable_text_field
description: A simple text field with scroll capability.
version: 0.0.1
homepage: https://github.com/DustinPark92/nice-scrollable-text-field

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
